---
os: linux
dist: bionic
language: python
python:
  - "3.8"
services:
  - docker

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1
  jobs:
    - MOLECULE_DISTRO=ubuntu1604
    - MOLECULE_DISTRO=ubuntu1804
    - MOLECULE_DISTRO=ubuntu2004

jobs:
  allow_failures:
    - env:
        MOLECULE_DISTRO=ubuntu1604

before_install:
  - sudo apt-get -qq update
  - pip install --upgrade pipenv

install:
  - yes | pipenv install --deploy

script:
  - pipenv run molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
