---
galaxy_info:
  author: Jonathan Hanson
  description: Configuring `nftables` for gateway routing and NAT
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
  galaxy_tags:
    - nftables
    - nat
    - routing
