---
sudo: required

dist: xenial

language: python

python: 3.7

services:
  - docker

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1

before_install:
  - pip install --upgrade pipenv

install:
  - yes | pipenv install --dev --deploy

script:
  - pipenv run molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
