---
language: python
python:
  - "3.7"

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1

sudo: required

services:
  - docker

install:
  - pip install pipenv
  - yes | pipenv install --deploy

script:
  - pipenv run molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
