---
- name: Reload ipv4 iptables
  ansible.builtin.shell: "iptables-restore < /etc/iptables/rules.v4"
  changed_when: True

# - name: Reload ipv6 iptables
#   ansible.builtin.shell: "iptables-restore < /etc/iptables/rules.v6"
#   changed_when: True
