---
- name: Ensure VLAN package is present
  ansible.builtin.package:
    name: vlan
    state: present
  notify: Restart networking

- name: Ensure 802.1q kernel module is loaded
  community.general.modprobe:
    name: 8021q
    state: present
  notify: Restart networking

- name: Ensure 802.1q kernel module is always loaded on boot
  ansible.builtin.lineinfile:
    path: /etc/modules
    line: "8021q"
  notify: Restart networking

- name: Ensure netplan is not installed
  ansible.builtin.package:
    name: netplan.io
    state: absent
  notify: Restart networking

- name: Ensure ifupdown is installed
  ansible.builtin.package:
    name: ifupdown
    state: present
  notify: Restart networking

- name: Ensure the network interfaces are configured
  ansible.builtin.template:
    src: network_interfaces.j2
    dest: /etc/network/interfaces
    mode: "0644"
  notify: Restart networking

- name: Ensure network changes take effect before we go on
  ansible.builtin.meta: flush_handlers
