---
- name: Ensure VLAN package is present
  ansible.builtin.package:
    name: vlan
    state: present
  notify: Restart networking

- name: Ensure 802.1q kernel module is loaded
  community.general.modprobe:
    name: 8021q
    state: present
  notify: Restart networking

- name: Ensure 802.1q kernel module is always loaded on boot
  ansible.builtin.lineinfile:
    path: /etc/modules
    line: "8021q"
  notify: Restart networking

- name: Old networking
  when: true
  block:
    - name: Ensure netplan is not installed
      ansible.builtin.package:
        name: netplan.io
        state: absent
      notify: Restart networking

    - name: Ensure ifupdown is installed
      ansible.builtin.package:
        name: ifupdown
        state: present
      notify: Restart networking

    - name: Ensure the network interfaces are configured
      ansible.builtin.template:
        src: network_interfaces.j2
        dest: /etc/network/interfaces
        mode: "0644"
      notify: Restart networking

- name: New networking
  when: false
  block:
    - name: Ensure netplan is installed
      ansible.builtin.package:
        name: netplan.io
        state: present
      notify: Restart networking

    - name: Ensure ifupdown is not installed
      ansible.builtin.package:
        name: ifupdown
        state: absent
      notify: Restart networking

    # something something systemd-networkd

- name: Ensure isc-dhcp is not installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  notify: Restart networking
  with_items:
    - isc-dhcp-client
    - isc-dhcp-common

- name: Ensure dhcpcd is installed
  ansible.builtin.package:
    name: dhcpcd
    state: present
  notify: Restart networking

- name: Ensure the network interfaces are configured
  ansible.builtin.template:
    src: dhcpcd.conf.j2
    dest: /etc/dhcpcd.conf
    mode: "0644"
  notify: Restart networking

- name: Ensure network changes take effect before we go on
  ansible.builtin.meta: flush_handlers
