---
- name: Prepare
  hosts: all
  pre_tasks:
    - name: Update the apt-cache, if necessary
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400
      when: ansible_facts['os_family'] == 'Debian'
    - name: Ensure some basic packages are available
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - dirmngr
