---

- name: Ensure iptables-persistent is removed
  ansible.builtin.package:
    name: iptables-persistent
    state: absent

- name: Ensure nftables is installed
  ansible.builtin.package:
    name: nftables
    state: present

- name: Ensure the nftables configuration file is in place
  ansible.builtin.template:
    src: nftables_config.j2
    dest: /etc/nftables.conf
    mode: "0644"
  notify: Reload nftables

- name: Ensure that nftables is started and enabled
  ansible.builtin.service:
    name: nftables
    state: started
    enabled: true

- name: Ensure firewall changes take effect before we go on
  ansible.builtin.meta: flush_handlers

- name: Ensure that ipv4 forwarding is enabled
  ansible.posix.sysctl:
    name: "net.ipv4.ip_forward"
    value: "1"
    sysctl_set: true
    state: present
    reload: true

- name: Ensure that ipv6 forwarding is enabled
  ansible.posix.sysctl:
    name: "net.ipv6.conf.all.forwarding"
    value: "1"
    sysctl_set: true
    state: present
    reload: true
