---
- name: Ensure dnsmasq is installed
  ansible.builtin.package:
    name: dnsmasq
    state: present

- name: Ensure dnsmasq config file is installed
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    validate: /usr/sbin/dnsmasq -C %s --test
    mode: "0644"
  notify: Restart dnsmasq

- name: Ensure systemd-resolved isn't set up to listen on port 53
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: "DNSStubListener="
    line: "DNSStubListener=no"
  notify: Restart resolved

- name: Ensure dnsmasq starts before systemd-resolved
  ansible.builtin.lineinfile:
    path: /etc/systemd/system/multi-user.target.wants/dnsmasq.service
    insertafter: "[Unit]"
    regexp: "^Before=systemd-resolved.service"
    line: "Before=systemd-resolved.service"
  notify:
    - Reload systemd
    - Restart resolved
    - Restart dnsmasq

- name: Ensure Dnsmasq changes take effect before we go on
  ansible.builtin.meta: flush_handlers
