---
- name: Ensure dnsmasq is installed
  package: name=dnsmasq state=present

- name: Ensure dnsmasq config file is installed
  template:
      src: dnsmasq.conf.j2
      dest: /etc/dnsmasq.conf
      validate: /usr/sbin/dnsmasq -C %s --test
  notify: restart dnsmasq
