---
# Network interface definitions, such that they'll appear
# in /etc/network/interfaces
network_interfaces: []
  # - { comment: "WAN",             # Comment block which will be inserted into the /etc/network/interfaces file
  #     interface: eth0,            # The interface name
  #     configuration: dhcp         # How the interface is configured - `manual`, `dhcp`, `static`, etc
                                    #
                                    # Additional allowed fields include `address`, `netmask`,
                                    #   `gateway`, `network`, `broadcast`, and `vlan_device`
  #   }
  # - { comment: "LAN",             # As another example...
  #     interface: eth1,
  #     configuration: static,
  #     address: "192.168.0.1",
  #     netmask: "255.255.255.0",
  #     network: "192.168.0.0",
  #     broadcast: "192.168.0.255"
  #   }

# Count, in frames, for the size of the transmit queue lengths.  This value
# will be set on all interface defined in network_interfaces.
# 1000 was the default value on a stock Ubuntu Xenial install.
network_interfaces_txqueue_length: 1000
