---
- name: Ensure Wireguard is installed
  package:
    name: wireguard
    state: present

- name: Process a wireguard interface definition
  include_tasks: interface.yml
  with_items: "{{ wireguard_interfaces }}"

- name: Ensure the service is enabled and started
  service:
    name: "wg-quick@{{ item.name }}"
    state: started
    enabled: yes
  with_items: "{{ wireguard_interfaces }}"
  no_log: true
